### ISSUE TITLE
(NOT CODE RELATED) study for evaluation (see underneath)

### ISSUE THREAD

**Issue by Raavkoper** [AtibQur/Webserv#21]
In de sheet staan heeeeeel veel punten over dingen waar ik in ieder geval niet bekend mee ben. Het lijkt me handig om dit een beetje op te splitten en hierover te leren, zodat de eval op dat kader iig goed gaat. Wie weet helpt t nog oprecht met webserv ook!:)

**Comment by steryu** [comment]
ik heb de eval sheet!

**Comment by Raavkoper** [comment]
good busy! :))
