### ISSUE TITLE
infinite loop when (curl -X POST https://localhost:8081 -d "hi=doei")

### ISSUE THREAD

**Issue by Raavkoper** [AtibQur/Webserv#85]
in de isRequestComplete functie gebeurd wat rare shit
als je deze curl request maakt loop hij ook vast
kus
wow jij bent echt cool
wil je trouw?
ik val op mannen :(
NIETES
prank
val op jou
ok nog een kus

**Comment by Raavkoper** [comment]
https oeps, maar bestaat wel

**Comment by steryu** [comment]
oke
