### ISSUE TITLE
Comments in Configfile do not work

### ISSUE THREAD

**Issue by AtibQur** [AtibQur/Webserv#92]
Als ik autoindex on heb staan bij bijvoorbeeld het blok location /, en daarna de autoindex uit comment, dan krijg ik de auto index nog steeds te zien. Gebeurt soms, niet elke keer. Hoe werkt config file met comments?

**Comment by Raavkoper** [comment]
een hashtag ervoor comment de hele line uit en een comment daarna kan om je line te beschrijven
